export interface InnerGroup {
  name: string;
  iconName: string;
  accent: 'emerald' | 'amber' | 'sky' | 'rose' | 'violet' | 'cyan' | 'orange' | 'pink' | 'blue' | 'mature';
  link: string;
  span?: 'lg' | 'wide';
  mature?: boolean;
}

export const MAIN_WHATSAPP_LINK = 'https://chat.whatsapp.com/bs-realms-main';

export const INNER_GROUPS: InnerGroup[] = [
  { name: 'BS Realms', iconName: 'Globe', accent: 'emerald', link: 'https://chat.whatsapp.com/bs-realms', span: 'lg' },
  { name: 'Skills', iconName: 'Zap', accent: 'amber', link: 'https://chat.whatsapp.com/skills' },
  { name: 'Addons and Mods', iconName: 'Package', accent: 'sky', link: 'https://chat.whatsapp.com/addons-mods', span: 'wide' },
  { name: 'PVP ⚔️', iconName: 'Swords', accent: 'rose', link: 'https://chat.whatsapp.com/pvp' },
  { name: 'Horror 👻', iconName: 'Ghost', accent: 'violet', link: 'https://chat.whatsapp.com/horror' },
  { name: 'Only for Legends 👑', iconName: 'Crown', accent: 'amber', link: 'https://chat.whatsapp.com/legends' },
  { name: 'Events 📅', iconName: 'Calendar', accent: 'cyan', link: 'https://chat.whatsapp.com/events' },
  { name: 'Lifesteal ❤️‍🔥', iconName: 'Heart', accent: 'rose', link: 'https://chat.whatsapp.com/lifesteal' },
  { name: 'Anarchy 🧨', iconName: 'Flame', accent: 'orange', link: 'https://chat.whatsapp.com/anarchy' },
  { name: 'Rich 🤑 💎 💰 💸', iconName: 'Coins', accent: 'emerald', link: 'https://chat.whatsapp.com/rich' },
  { name: 'Party 🎉', iconName: 'PartyPopper', accent: 'pink', link: 'https://chat.whatsapp.com/party' },
  { name: 'RPG 🛡️', iconName: 'Shield', accent: 'blue', link: 'https://chat.whatsapp.com/rpg' },
  { name: 'DORO (Only for 18+ 🔞)', iconName: 'Skull', accent: 'mature', link: 'https://chat.whatsapp.com/doro', mature: true, span: 'wide' },
];

export const ACCENT_STYLES = {
  emerald: {
    glow: 'group-hover:shadow-[0_0_40px_-8px_rgba(52,211,153,0.6)]',
    iconBg: 'from-emerald-500/20 to-emerald-500/5',
    iconText: 'text-emerald-300',
    ring: 'group-hover:border-emerald-400/40',
    beam: 'from-emerald-500/0 via-emerald-400/30 to-emerald-500/0',
  },
  amber: {
    glow: 'group-hover:shadow-[0_0_40px_-8px_rgba(251,191,36,0.6)]',
    iconBg: 'from-amber-500/20 to-amber-500/5',
    iconText: 'text-amber-300',
    ring: 'group-hover:border-amber-400/40',
    beam: 'from-amber-500/0 via-amber-400/30 to-amber-500/0',
  },
  sky: {
    glow: 'group-hover:shadow-[0_0_40px_-8px_rgba(56,189,248,0.6)]',
    iconBg: 'from-sky-500/20 to-sky-500/5',
    iconText: 'text-sky-300',
    ring: 'group-hover:border-sky-400/40',
    beam: 'from-sky-500/0 via-sky-400/30 to-sky-500/0',
  },
  rose: {
    glow: 'group-hover:shadow-[0_0_40px_-8px_rgba(251,113,133,0.6)]',
    iconBg: 'from-rose-500/20 to-rose-500/5',
    iconText: 'text-rose-300',
    ring: 'group-hover:border-rose-400/40',
    beam: 'from-rose-500/0 via-rose-400/30 to-rose-500/0',
  },
  violet: {
    glow: 'group-hover:shadow-[0_0_40px_-8px_rgba(167,139,250,0.6)]',
    iconBg: 'from-violet-500/20 to-violet-500/5',
    iconText: 'text-violet-300',
    ring: 'group-hover:border-violet-400/40',
    beam: 'from-violet-500/0 via-violet-400/30 to-violet-500/0',
  },
  cyan: {
    glow: 'group-hover:shadow-[0_0_40px_-8px_rgba(34,211,238,0.6)]',
    iconBg: 'from-cyan-500/20 to-cyan-500/5',
    iconText: 'text-cyan-300',
    ring: 'group-hover:border-cyan-400/40',
    beam: 'from-cyan-500/0 via-cyan-400/30 to-cyan-500/0',
  },
  orange: {
    glow: 'group-hover:shadow-[0_0_40px_-8px_rgba(251,146,60,0.6)]',
    iconBg: 'from-orange-500/20 to-orange-500/5',
    iconText: 'text-orange-300',
    ring: 'group-hover:border-orange-400/40',
    beam: 'from-orange-500/0 via-orange-400/30 to-orange-500/0',
  },
  pink: {
    glow: 'group-hover:shadow-[0_0_40px_-8px_rgba(244,114,182,0.6)]',
    iconBg: 'from-pink-500/20 to-pink-500/5',
    iconText: 'text-pink-300',
    ring: 'group-hover:border-pink-400/40',
    beam: 'from-pink-500/0 via-pink-400/30 to-pink-500/0',
  },
  blue: {
    glow: 'group-hover:shadow-[0_0_40px_-8px_rgba(96,165,250,0.6)]',
    iconBg: 'from-blue-500/20 to-blue-500/5',
    iconText: 'text-blue-300',
    ring: 'group-hover:border-blue-400/40',
    beam: 'from-blue-500/0 via-blue-400/30 to-blue-500/0',
  },
  mature: {
    glow: 'group-hover:shadow-[0_0_40px_-8px_rgba(239,68,68,0.7)]',
    iconBg: 'from-red-500/25 to-red-500/10',
    iconText: 'text-red-400',
    ring: 'group-hover:border-red-500/50',
    beam: 'from-red-500/0 via-red-400/40 to-red-500/0',
  },
};

export const LANGUAGES = [
  { code: 'en', label: 'English', flag: '🇺🇸' },
  { code: 'es', label: 'Español', flag: '🇪🇸' },
  { code: 'fr', label: 'Français', flag: '🇫🇷' },
  { code: 'pt', label: 'Português', flag: '🇧🇷' },
  { code: 'ar', label: 'العربية', flag: '🇸🇦' },
  { code: 'hi', label: 'हिन्दी', flag: '🇮🇳' },
];

export const TRANSLATIONS: Record<string, any> = {
  en: {
    dir: 'ltr',
    nav: { community: 'Community', innergroups: 'Innergroups', rules: 'Rules', join: 'Join WhatsApp' },
    hero: {
      badge: 'THE ULTIMATE MINECRAFT COMMUNITY ON WHATSAPP',
      title: 'Welcome to BS Realms',
      subtitle: 'The ultimate Minecraft community on WhatsApp. Find your realm, join the adventure, and forge lasting friendships.',
      cta: 'Join Community',
      secondary: 'Explore Innergroups',
      scroll: 'Scroll to explore',
    },
    groups: {
      title: 'Thirteen Realms Await You',
      subtitle: 'Choose your path. Each innergroup is a vibrant community inside BS Realms tailored for specific playstyles.',
      warning: '18+ Strictly Required',
      join: 'Open Group',
    },
    stats: {
      title: 'Community at a Glance',
      subtitle: 'Real players. Real realms. One unstoppable Minecraft community.',
      members: 'Total Members',
      servers: 'Active Servers',
      groups: 'Innergroups',
      eventsHosted: 'Events Hosted',
    },
    events: {
      title: 'Events',
      comingSoon: 'COMING SOON',
      subtitle: 'Tournaments, seasonal festivals, and live community events are on the way.',
      stayTuned: 'Stay tuned — epic events are being forged in the background.',
    },
    footer: {
      tagline: 'The ultimate Minecraft community on WhatsApp.',
      rules: 'Community Rules',
      social: 'Follow Us',
      rights: 'All rights reserved.',
      joinCta: 'Ready to Join the Adventure?',
      made: 'Crafted for the BS Realms Community',
    },
    modal18: {
      title: 'Age Verification Required',
      subtitle: 'This group contains mature 18+ content. Please confirm that you are at least 18 years old to proceed.',
      confirm: 'I am 18 or older',
      cancel: 'Go Back',
    },
    modalRules: {
      title: 'BS Realms Community Rules',
      subtitle: 'Please adhere to these guidelines to maintain a fun, safe, and respectful environment for everyone.',
      close: 'Got It',
    },
    rulesList: [
      { title: 'Be Respectful', desc: 'Treat all community members with kindness and respect. No harassment or hate speech.' },
      { title: 'No Spamming', desc: 'Keep self-promotion and repetitive messages out of public channels.' },
      { title: 'Stay On Topic', desc: 'Ensure discussions align with the specific group theme and Minecraft.' },
      { title: 'Age Scoped Content', desc: 'Mature 18+ discussions are strictly confined to the designated DORO group.' },
      { title: 'Follow Admin Orders', desc: 'Respect decisions and moderation directions given by community admins.' },
    ],
    descriptions: {
      'BS Realms': 'The flagship survival and creative realms of BS Realms.',
      Skills: 'Master skills, level up your character, and build your legacy.',
      'Addons and Mods': 'Custom addons, mods, and resource packs curated by the community.',
      'PVP ⚔️': 'Prove your might in ranked and casual PvP arenas.',
      'Horror 👻': 'Spine-chilling maps, jump scares, and survival horror events.',
      'Only for Legends 👑': 'An elite circle reserved for the most dedicated players.',
      'Events 📅': 'Tournaments, seasonal festivals, and live community events.',
      'Lifesteal ❤️‍🔥': 'Steal hearts, lose hearts — high-stakes survival chaos.',
      'Anarchy 🧨': 'No rules. No mercy. Pure unfiltered Minecraft anarchy.',
      'Rich 🤑 💎 💰 💸': 'Economy, trading, and flex your in-game wealth.',
      'Party 🎉': 'Hang out, minigames, and good vibes only.',
      'RPG 🛡️': 'Quests, classes, and deep roleplaying adventures.',
      'DORO (Only for 18+ 🔞)': 'Mature content channel. Strictly 18+. Enter at your own risk.',
    },
  },
  es: {
    dir: 'ltr',
    nav: { community: 'Comunidad', innergroups: 'Subgrupos', rules: 'Reglas', join: 'Unirse' },
    hero: {
      badge: 'LA COMUNIDAD DEFINITIVA DE MINECRAFT EN WHATSAPP',
      title: 'Bienvenido a BS Realms',
      subtitle: 'La comunidad definitiva de Minecraft en WhatsApp. Encuentra tu reino y únete a la aventura.',
      cta: 'Unirse a la Comunidad',
      secondary: 'Explorar Subgrupos',
      scroll: 'Desplaza para explorar',
    },
    groups: {
      title: 'Trece Reinos te Esperan',
      subtitle: 'Elige tu camino. Cada subgrupo es una comunidad vibrante dentro de BS Realms.',
      warning: 'Solo 18+',
      join: 'Abrir Grupo',
    },
    stats: {
      title: 'Comunidad de un Vistazo',
      subtitle: 'Jugadores reales. Reinos reales. Una comunidad imparable.',
      members: 'Miembros Totales',
      servers: 'Servidores Activos',
      groups: 'Subgrupos',
      eventsHosted: 'Eventos Realizados',
    },
    events: {
      title: 'Eventos',
      comingSoon: 'PRÓXIMAMENTE',
      subtitle: 'Torneos, festivales estacionales y eventos en vivo en camino.',
      stayTuned: 'Mantente al tanto — grandes eventos se están preparando.',
    },
    footer: {
      tagline: 'La comunidad definitiva de Minecraft en WhatsApp.',
      rules: 'Reglas de la Comunidad',
      social: 'Síguenos',
      rights: 'Todos los derechos reservados.',
      joinCta: '¿Listo para unirte a la aventura?',
      made: 'Creado para la Comunidad BS Realms',
    },
    modal18: {
      title: 'Verificación de Edad Requerida',
      subtitle: 'Este grupo contiene contenido maduro para mayores de 18 años. Confirma que tienes al menos 18 años.',
      confirm: 'Tengo 18 años o más',
      cancel: 'Volver',
    },
    modalRules: {
      title: 'Reglas de la Comunidad BS Realms',
      subtitle: 'Respeta estas normas para mantener un entorno divertido y seguro.',
      close: 'Entendido',
    },
    rulesList: [
      { title: 'Respeta a Todos', desc: 'Trata a todos los miembros con amabilidad. Sin acoso ni discriminación.' },
      { title: 'Sin Spam', desc: 'Evita el spam y la publicidad no autorizada en los grupos.' },
      { title: 'Mantén el Tema', desc: 'Asegúrate de hablar sobre Minecraft y la temática del grupo.' },
      { title: 'Contenido +18 Acotado', desc: 'Contenido maduro reservado estrictamente al grupo DORO.' },
      { title: 'Sigue las Reglas', desc: 'Respeta las decisiones tomadas por los administradores.' },
    ],
    descriptions: {
      'BS Realms': 'Los mundos principales de supervivencia y creatividad.',
      Skills: 'Domina habilidades y sube de nivel.',
      'Addons and Mods': 'Addons, mods y packs de recursos personalizados.',
      'PVP ⚔️': 'Demuestra tu poder en arenas PvP casuales y competitivas.',
      'Horror 👻': 'Mapas escalofriantes, sustos y eventos de terror.',
      'Only for Legends 👑': 'Un círculo de élite reservado para los más dedicados.',
      'Events 📅': 'Torneos, festivales estacionales y eventos en vivo.',
      'Lifesteal ❤️‍🔥': 'Roba corazones, pierde corazones — caos de supervivencia.',
      'Anarchy 🧨': 'Sin reglas. Sin piedad. Anarquía pura de Minecraft.',
      'Rich 🤑 💎 💰 💸': 'Economía, comercio y presume tu riqueza en el juego.',
      'Party 🎉': 'Relájate, minijuegos y solo buenas vibras.',
      'RPG 🛡️': 'Misiones, clases y aventuras de rol profundas.',
      'DORO (Only for 18+ 🔞)': 'Canal de contenido maduro. Estrictamente 18+.',
    },
  },
  fr: {
    dir: 'ltr',
    nav: { community: 'Communauté', innergroups: 'Sous-groupes', rules: 'Règles', join: 'Rejoindre' },
    hero: {
      badge: 'LA COMMUNAUTÉ MINECRAFT ULTIME SUR WHATSAPP',
      title: 'Bienvenue sur BS Realms',
      subtitle: 'La communauté Minecraft ultime sur WhatsApp. Trouvez votre royaume et rejoignez l’aventure.',
      cta: 'Rejoindre la Communauté',
      secondary: 'Explorer les Sous-groupes',
      scroll: 'Faites défiler pour explorer',
    },
    groups: {
      title: 'Treize Royaumes Vous Attendent',
      subtitle: 'Choisissez votre voie. Chaque sous-groupe est une communauté passionnée au sein de BS Realms.',
      warning: 'Réservé aux +18',
      join: 'Ouvrir le Groupe',
    },
    stats: {
      title: 'La Communauté en un coup d’œil',
      subtitle: 'De vrais joueurs. De vrais royaumes. Une communauté imbattable.',
      members: 'Membres Totaux',
      servers: 'Serveurs Actifs',
      groups: 'Sous-groupes',
      eventsHosted: 'Événements Organisés',
    },
    events: {
      title: 'Événements',
      comingSoon: 'PROCHAINEMENT',
      subtitle: 'Tournois, festivals saisonniers et événements en direct à venir.',
      stayTuned: 'Restez à l’affût — des événements épiques se préparent.',
    },
    footer: {
      tagline: 'La communauté Minecraft ultime sur WhatsApp.',
      rules: 'Règles de la Communauté',
      social: 'Suivez-nous',
      rights: 'Tous droits réservés.',
      joinCta: 'Prêt à rejoindre l’aventure ?',
      made: 'Conçu pour la Communauté BS Realms',
    },
    modal18: {
      title: 'Vérification d’âge requise',
      subtitle: 'Ce groupe contient du contenu réservé aux adultes (+18). Veuillez confirmer votre âge.',
      confirm: 'J’ai 18 ans ou plus',
      cancel: 'Retour',
    },
    modalRules: {
      title: 'Règles de la Communauté BS Realms',
      subtitle: 'Veuillez respecter ces règles pour garantir une ambiance saine et conviviale.',
      close: 'Compris',
    },
    rulesList: [
      { title: 'Respectez Chacun', desc: 'Faites preuve de bienveillance envers tous les membres.' },
      { title: 'Pas de Spam', desc: 'Évitez la publicité excessive et les messages répétitifs.' },
      { title: 'Restez dans le Sujet', desc: 'Discutez de Minecraft et des thématiques associées.' },
      { title: 'Contenu +18 Limité', desc: 'Contenu adulte strictement réservé au canal DORO.' },
      { title: 'Respectez les Admins', desc: 'Suivez les consignes de modération.' },
    ],
    descriptions: {
      'BS Realms': 'Les royaumes emblématiques de survie et création.',
      Skills: 'Maîtrisez des compétences et gagnez des niveaux.',
      'Addons and Mods': 'Addons et packs de ressources créés par la communauté.',
      'PVP ⚔️': 'Prouvez votre force dans des arènes PvP classées.',
      'Horror 👻': 'Cartes glaçantes, jump scares et événements d’horreur.',
      'Only for Legends 👑': 'Cercle d’élite réservé aux joueurs chevronnés.',
      'Events 📅': 'Tournois, festivals et animations en direct.',
      'Lifesteal ❤️‍🔥': 'Volez des cœurs — mode survie impitoyable.',
      'Anarchy 🧨': 'Aucune règle. Aucune pitié. Anarchie totale.',
      'Rich 🤑 💎 💰 💸': 'Économie, commerce et étalage de richesse.',
      'Party 🎉': 'Détente, mini-jeux et bonne ambiance.',
      'RPG 🛡️': 'Quêtes, classes et aventures de rôle.',
      'DORO (Only for 18+ 🔞)': 'Canal de contenu mature. Strictement 18+.',
    },
  },
  pt: {
    dir: 'ltr',
    nav: { community: 'Comunidade', innergroups: 'Subgrupos', rules: 'Regras', join: 'Entrar' },
    hero: {
      badge: 'A COMUNIDADE DEFINITIVA DE MINECRAFT NO WHATSAPP',
      title: 'Bem-vindo à BS Realms',
      subtitle: 'A comunidade definitiva de Minecraft no WhatsApp. Encontre seu reino e entre na aventura.',
      cta: 'Entrar na Comunidade',
      secondary: 'Explorar Subgrupos',
      scroll: 'Role para explorar',
    },
    groups: {
      title: 'Treze Reinos Esperam por Você',
      subtitle: 'Escolha seu caminho. Cada subgrupo é uma comunidade vibrante dentro da BS Realms.',
      warning: 'Apenas 18+',
      join: 'Abrir Grupo',
    },
    stats: {
      title: 'Visão Geral da Comunidade',
      subtitle: 'Jogadores reais. Reinos reais. Uma comunidade imbatível.',
      members: 'Membros Totais',
      servers: 'Servidores Ativos',
      groups: 'Subgrupos',
      eventsHosted: 'Eventos Realizados',
    },
    events: {
      title: 'Eventos',
      comingSoon: 'EM BREVE',
      subtitle: 'Torneios, festivais sazonais e eventos ao vivo estão a caminho.',
      stayTuned: 'Fique atento — grandes eventos estão sendo criados.',
    },
    footer: {
      tagline: 'A comunidade definitiva de Minecraft no WhatsApp.',
      rules: 'Regras da Comunidade',
      social: 'Siga-nos',
      rights: 'Todos os direitos reservados.',
      joinCta: 'Pronto para entrar na aventura?',
      made: 'Desenvolvido para a Comunidade BS Realms',
    },
    modal18: {
      title: 'Verificação de Idade Necessária',
      subtitle: 'Este grupo contém conteúdo adulto para maiores de 18 anos. Confirme se você possui 18 anos ou mais.',
      confirm: 'Tenho 18 anos ou mais',
      cancel: 'Voltar',
    },
    modalRules: {
      title: 'Regras da Comunidade BS Realms',
      subtitle: 'Siga estas regras para garantir um ambiente divertido e respeitoso.',
      close: 'Entendido',
    },
    rulesList: [
      { title: 'Respeite a Todos', desc: 'Trate todos os membros com educação e respeito.' },
      { title: 'Sem Spam', desc: 'Proibido spam e divulgação não autorizada.' },
      { title: 'Foco no Tema', desc: 'Mantenha o assunto focado em Minecraft e no tema do grupo.' },
      { title: 'Conteúdo +18 Restrito', desc: 'Conteúdo adulto restrito exclusivamente ao canal DORO.' },
      { title: 'Siga os Admins', desc: 'Respeite as instruções da moderação.' },
    ],
    descriptions: {
      'BS Realms': 'Mundos de sobrevivência e criação da BS Realms.',
      Skills: 'Aprenda habilidades e evolua no jogo.',
      'Addons and Mods': 'Addons e mods personalizados da comunidade.',
      'PVP ⚔️': 'Prove sua força em arenas PvP disputadas.',
      'Horror 👻': 'Mapas aterrorizantes e eventos de horror.',
      'Only for Legends 👑': 'Círculo de elite para os jogadores dedicados.',
      'Events 📅': 'Torneios e eventos ao vivo.',
      'Lifesteal ❤️‍🔥': 'Roube corações e sobreviva ao caos.',
      'Anarchy 🧨': 'Sem regras. Sem piedade. Anarquia pura.',
      'Rich 🤑 💎 💰 💸': 'Economia, comércio e ostentação.',
      'Party 🎉': 'Diversão, minijogos e boas vibrações.',
      'RPG 🛡️': 'Missões, classes e aventuras de RPG.',
      'DORO (Only for 18+ 🔞)': 'Canal de conteúdo adulto. Estritamente +18.',
    },
  },
  ar: {
    dir: 'rtl',
    nav: { community: 'المجتمع', innergroups: 'المجموعات الفرعية', rules: 'القوانين', join: 'انضمام' },
    hero: {
      badge: 'مجتمع ماينكرافت الأفضل على واتساب',
      title: 'مرحباً بكم في BS Realms',
      subtitle: 'مجتمع ماينكرافت الأفضل على واتساب. اعثر على عالمك وانضم إلى المغامرة الشيقة.',
      cta: 'انضم للمجتمع',
      secondary: 'استكشف المجموعات',
      scroll: 'مرر للاستكشاف',
    },
    groups: {
      title: 'ثلاثة عشر عالماً بانتظارك',
      subtitle: 'اختر مسارك. كل مجموعة فرعية هي مجتمع حيوي ومتكامل داخل BS Realms.',
      warning: 'للبالغين 18+ فقط',
      join: 'فتح المجموعة',
    },
    stats: {
      title: 'لمحة عن المجتمع',
      subtitle: 'لاعبون حقيقيون. عوالم حقيقية. مجتمع ماينكرافت لا يقهر.',
      members: 'إجمالي الأعضاء',
      servers: 'السيرفرات النشطة',
      groups: 'المجموعات الفرعية',
      eventsHosted: 'الفعاليات المنظمة',
    },
    events: {
      title: 'الفعاليات',
      comingSoon: 'قريباً',
      subtitle: 'بطولات ومهرجانات موسمية وأحداث مباشرة في الطريق إليكم.',
      stayTuned: 'ترقبوا — أحداث ملحمية قادمة.',
    },
    footer: {
      tagline: 'مجتمع ماينكرافت الأفضل على واتساب.',
      rules: 'قوانين المجتمع',
      social: 'تابعنا',
      rights: 'جميع الحقوق محفوظة.',
      joinCta: 'هل أنت جاهز للانضمام إلى المغامرة؟',
      made: 'صُمم لمجتمع BS Realms',
    },
    modal18: {
      title: 'تأكيد العمر مطلوب',
      subtitle: 'تحتوي هذه المجموعة على محتوى مخصص للبالغين (+18). يرجى تأكيد أن عمرك 18 عاماً أو أكثر.',
      confirm: 'عمري 18 عاماً أو أكثر',
      cancel: 'الرجوع',
    },
    modalRules: {
      title: 'قوانين مجتمع BS Realms',
      subtitle: 'يرجى الالتزام بهاتين القواعد للحفاظ على بيئة ممتعة وآمنة للجميع.',
      close: 'فهمت',
    },
    rulesList: [
      { title: 'احترام الجميع', desc: 'تعامل مع جميع الأعضاء بلطف واحترام. يمنع التنمر كلياً.' },
      { title: 'لا للإزعاج والسبام', desc: 'يمنع نشر الرسائل التكرارية أو الإعلانات غير المصرح بها.' },
      { title: 'الالتزام بموضوع المجموعة', desc: 'تأكد من أن النقاشات متعلقة بـ ماينكرافت وموضوع المجموعة.' },
      { title: 'محتوى +18 محصور', desc: 'المحتوى المخصص للبالغين محصور فقط في مجموعة DORO.' },
      { title: 'اتبع تعليمات المشرفين', desc: 'احترم القرارات والتوجيهات الصادرة من إدارة المجتمع.' },
    ],
    descriptions: {
      'BS Realms': 'عوالم البقاء والإبداع الرئيسية لـ BS Realms.',
      Skills: 'أتقن المهارات، ارتقِ بمستواك واصنع أسطورتك.',
      'Addons and Mods': 'إضافات ومودات وحزم موارد مخصصة من المجتمع.',
      'PVP ⚔️': 'أثبت قوتك في ساحات PvP تنافسية وودية.',
      'Horror 👻': 'خرائط مرعبة ومفاجئات وأحداث رعب.',
      'Only for Legends 👑': 'دائرة النخبة المخصصة لأكثر اللاعبين تفانياً.',
      'Events 📅': 'بطولات ومهرجانات موسمية وأحداث مباشرة.',
      'Lifesteal ❤️‍🔥': 'اسرق القلوب، اخسر القلوب — فوضى بقاء عالية المخاطر.',
      'Anarchy 🧨': 'لا قوانين. لا رحمة. فوضى ماينكرافت الخالصة.',
      'Rich 🤑 💎 💰 💸': 'اقتصاد وتجارة وأظهر ثروتك في اللعبة.',
      'Party 🎉': 'استرخِ، ألعاب مصغرة وأجواء رائعة فقط.',
      'RPG 🛡️': 'مهام، فئات، ومغامرات لعب أدوار عميقة.',
      'DORO (Only for 18+ 🔞)': 'قناة محتوى للبالغين. 18+ فقط. ادخل على مسؤوليتك.',
    },
  },
  hi: {
    dir: 'ltr',
    nav: { community: 'समुदाय', innergroups: 'उप-समूह', rules: 'नियम', join: 'शामिल हों' },
    hero: {
      badge: 'WHATSAPP पर अंतिम MINECRAFT समुदाय',
      title: 'BS Realms में आपका स्वागत है',
      subtitle: 'WhatsApp पर अंतिम Minecraft समुदाय। अपना राज्य खोजें और रोमांच में शामिल हों।',
      cta: 'समुदाय में शामिल हों',
      secondary: 'उप-समूह देखें',
      scroll: 'एक्सप्लोर करने के लिए स्क्रॉल करें',
    },
    groups: {
      title: 'तेरह राज्य आपकी प्रतीक्षा में',
      subtitle: 'अपना रास्ता चुनें। हर उप-समूह BS Realms के अंदर एक जीवंत समुदाय है।',
      warning: 'केवल 18+',
      join: 'समूह खोलें',
    },
    stats: {
      title: 'समुदाय एक नज़र में',
      subtitle: 'असली खिलाड़ी। असली राज्य। एक अजेय समुदाय।',
      members: 'कुल सदस्य',
      servers: 'सक्रिय सर्वर',
      groups: 'उप-समूह',
      eventsHosted: 'आयोजित कार्यक्रम',
    },
    events: {
      title: 'कार्यक्रम',
      comingSoon: 'जल्द आ रहा है',
      subtitle: 'टूर्नामेंट, मौसमी उत्सव और लाइव समुदाय कार्यक्रम रास्ते में हैं।',
      stayTuned: 'बने रहें — शानदार कार्यक्रम तैयार हो रहे हैं।',
    },
    footer: {
      tagline: 'WhatsApp पर अंतिम Minecraft समुदाय।',
      rules: 'समुदाय नियम',
      social: 'हमें फॉलो करें',
      rights: 'सर्वाधिकार सुरक्षित।',
      joinCta: 'रोमांच में शामिल होने के लिए तैयार?',
      made: 'BS Realms समुदाय के लिए बनाया गया',
    },
    modal18: {
      title: 'आयु सत्यापन आवश्यक',
      subtitle: 'इस समूह में 18+ वयस्क सामग्री है। कृपया पुष्टि करें कि आपकी आयु कम से कम 18 वर्ष है।',
      confirm: 'मेरी आयु 18 वर्ष या अधिक है',
      cancel: 'वापस जाएं',
    },
    modalRules: {
      title: 'BS Realms समुदाय नियम',
      subtitle: 'कृपया सभी के लिए एक सुरक्षित और सम्मानजनक वातावरण बनाए रखने के लिए इन नियमों का पालन करें।',
      close: 'समझ गया',
    },
    rulesList: [
      { title: 'सभी का सम्मान करें', desc: 'सभी सदस्यों के साथ विनम्रता से व्यवहार करें।' },
      { title: 'स्पैम न करें', desc: 'अनुचित विज्ञापन और बार-बार मैसेज न भेजें।' },
      { title: 'विषय पर रहें', desc: 'चर्चा Minecraft और समूह के विषय पर केंद्रित रखें।' },
      { title: '18+ सामग्री सीमित', desc: 'वयस्क सामग्री केवल DORO ग्रुप तक सीमित है।' },
      { title: 'एडमिन की बात मानें', desc: 'समुदाय एडमिन के निर्देशों का पालन करें।' },
    ],
    descriptions: {
      'BS Realms': 'BS Realms के प्रमुख सर्वाइवल और क्रिएटिव वर्ल्ड।',
      Skills: 'कौशल सीखें और लेवल बढ़ाएं।',
      'Addons and Mods': 'समुदाय द्वारा चुने गए कस्टम ऐडऑन और मॉड।',
      'PVP ⚔️': 'PvP अखाड़ों में अपनी ताकत साबित करें।',
      'Horror 👻': 'रोंगटे खड़े करने वाले मैप और हॉरर इवेंट।',
      'Only for Legends 👑': 'समर्पित खिलाड़ियों के लिए एलीट सर्कल।',
      'Events 📅': 'टूर्नामेंट और लाइव इवेंट।',
      'Lifesteal ❤️‍🔥': 'हार्ट चुराएं — सर्वाइवल का रोमांच।',
      'Anarchy 🧨': 'कोई नियम नहीं। शुद्ध Minecraft अराजकता।',
      'Rich 🤑 💎 💰 💸': 'अर्थव्यवस्था और ट्रेडिंग।',
      'Party 🎉': 'मिनीगेम्स और सिर्फ अच्छी वाइब्स।',
      'RPG 🛡️': 'क्वेस्ट और रोलप्लेइंग एडवेंचर।',
      'DORO (Only for 18+ 🔞)': 'वयस्क सामग्री चैनल। केवल 18+।',
    },
  },
};
